name: Node.js CICD
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  compile:
    runs-on: Agent-1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4


          
