name: Node.js CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  compile:
      runs-on: Agent-1
      
      steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '23'

        - name: Frontend Compilation (Syntax Check)
          run: |
            cd client
            find . -name "*.js" -exec node --check {} +

        - name: Backend Compilation (Syntax Check)
          run: |
            cd api
            find . -name "*.js" -exec node --check {} +
